/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VibeRouteImport } from './routes/vibe'
import { Route as VantagensRouteImport } from './routes/vantagens'
import { Route as SelectorRouteImport } from './routes/selector'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as RecommendationRouteImport } from './routes/recommendation'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as HarmonizacaoRouteImport } from './routes/harmonizacao'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ClubeRouteImport } from './routes/clube'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as ParceiroSlugRouteImport } from './routes/parceiro.$slug'
import { Route as KitIdRouteImport } from './routes/kit.$id'
import { Route as HarmonizacaoResultadoRouteImport } from './routes/harmonizacao_.resultado'
import { Route as ClubeIdRouteImport } from './routes/clube.$id'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminProdutosRouteImport } from './routes/_admin/admin.produtos'
import { Route as AdminAdminPedidosRouteImport } from './routes/_admin/admin.pedidos'
import { Route as AdminAdminClientesIndexRouteImport } from './routes/_admin/admin.clientes.index'
import { Route as AdminAdminClientesIdRouteImport } from './routes/_admin/admin.clientes.$id'

const VibeRoute = VibeRouteImport.update({
  id: '/vibe',
  path: '/vibe',
  getParentRoute: () => rootRouteImport,
} as any)
const VantagensRoute = VantagensRouteImport.update({
  id: '/vantagens',
  path: '/vantagens',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectorRoute = SelectorRouteImport.update({
  id: '/selector',
  path: '/selector',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationRoute = RecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmonizacaoRoute = HarmonizacaoRouteImport.update({
  id: '/harmonizacao',
  path: '/harmonizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeRoute = ClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceiroSlugRoute = ParceiroSlugRouteImport.update({
  id: '/parceiro/$slug',
  path: '/parceiro/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KitIdRoute = KitIdRouteImport.update({
  id: '/kit/$id',
  path: '/kit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmonizacaoResultadoRoute = HarmonizacaoResultadoRouteImport.update({
  id: '/harmonizacao_/resultado',
  path: '/harmonizacao/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeIdRoute = ClubeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClubeRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProdutosRoute = AdminAdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPedidosRoute = AdminAdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminClientesIndexRoute = AdminAdminClientesIndexRouteImport.update({
  id: '/admin/clientes/',
  path: '/admin/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminClientesIdRoute = AdminAdminClientesIdRouteImport.update({
  id: '/admin/clientes/$id',
  path: '/admin/clientes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/clube': typeof ClubeRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/contato': typeof ContatoRoute
  '/harmonizacao': typeof HarmonizacaoRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/promocoes': typeof PromocoesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recommendation': typeof RecommendationRoute
  '/redeem': typeof RedeemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/selector': typeof SelectorRoute
  '/vantagens': typeof VantagensRoute
  '/vibe': typeof VibeRoute
  '/clube/$id': typeof ClubeIdRoute
  '/harmonizacao/resultado': typeof HarmonizacaoResultadoRoute
  '/kit/$id': typeof KitIdRoute
  '/parceiro/$slug': typeof ParceiroSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/pedidos': typeof AdminAdminPedidosRoute
  '/admin/produtos': typeof AdminAdminProdutosRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/clientes/$id': typeof AdminAdminClientesIdRoute
  '/admin/clientes/': typeof AdminAdminClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/clube': typeof ClubeRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/contato': typeof ContatoRoute
  '/harmonizacao': typeof HarmonizacaoRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/promocoes': typeof PromocoesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recommendation': typeof RecommendationRoute
  '/redeem': typeof RedeemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/selector': typeof SelectorRoute
  '/vantagens': typeof VantagensRoute
  '/vibe': typeof VibeRoute
  '/clube/$id': typeof ClubeIdRoute
  '/harmonizacao/resultado': typeof HarmonizacaoResultadoRoute
  '/kit/$id': typeof KitIdRoute
  '/parceiro/$slug': typeof ParceiroSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/pedidos': typeof AdminAdminPedidosRoute
  '/admin/produtos': typeof AdminAdminProdutosRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/clientes/$id': typeof AdminAdminClientesIdRoute
  '/admin/clientes': typeof AdminAdminClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/clube': typeof ClubeRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/contato': typeof ContatoRoute
  '/harmonizacao': typeof HarmonizacaoRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/promocoes': typeof PromocoesRoute
  '/quem-somos': typeof QuemSomosRoute
  '/recommendation': typeof RecommendationRoute
  '/redeem': typeof RedeemRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/selector': typeof SelectorRoute
  '/vantagens': typeof VantagensRoute
  '/vibe': typeof VibeRoute
  '/clube/$id': typeof ClubeIdRoute
  '/harmonizacao_/resultado': typeof HarmonizacaoResultadoRoute
  '/kit/$id': typeof KitIdRoute
  '/parceiro/$slug': typeof ParceiroSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/_admin/admin/pedidos': typeof AdminAdminPedidosRoute
  '/_admin/admin/produtos': typeof AdminAdminProdutosRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/clientes/$id': typeof AdminAdminClientesIdRoute
  '/_admin/admin/clientes/': typeof AdminAdminClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/clube'
    | '/confirmation'
    | '/contato'
    | '/harmonizacao'
    | '/kits'
    | '/login'
    | '/perfil'
    | '/promocoes'
    | '/quem-somos'
    | '/recommendation'
    | '/redeem'
    | '/reset-password'
    | '/rewards'
    | '/selector'
    | '/vantagens'
    | '/vibe'
    | '/clube/$id'
    | '/harmonizacao/resultado'
    | '/kit/$id'
    | '/parceiro/$slug'
    | '/produto/$id'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/clube'
    | '/confirmation'
    | '/contato'
    | '/harmonizacao'
    | '/kits'
    | '/login'
    | '/perfil'
    | '/promocoes'
    | '/quem-somos'
    | '/recommendation'
    | '/redeem'
    | '/reset-password'
    | '/rewards'
    | '/selector'
    | '/vantagens'
    | '/vibe'
    | '/clube/$id'
    | '/harmonizacao/resultado'
    | '/kit/$id'
    | '/parceiro/$slug'
    | '/produto/$id'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin'
    | '/admin/clientes/$id'
    | '/admin/clientes'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/clube'
    | '/confirmation'
    | '/contato'
    | '/harmonizacao'
    | '/kits'
    | '/login'
    | '/perfil'
    | '/promocoes'
    | '/quem-somos'
    | '/recommendation'
    | '/redeem'
    | '/reset-password'
    | '/rewards'
    | '/selector'
    | '/vantagens'
    | '/vibe'
    | '/clube/$id'
    | '/harmonizacao_/resultado'
    | '/kit/$id'
    | '/parceiro/$slug'
    | '/produto/$id'
    | '/_admin/admin/pedidos'
    | '/_admin/admin/produtos'
    | '/_admin/admin/'
    | '/_admin/admin/clientes/$id'
    | '/_admin/admin/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  ClubeRoute: typeof ClubeRouteWithChildren
  ConfirmationRoute: typeof ConfirmationRoute
  ContatoRoute: typeof ContatoRoute
  HarmonizacaoRoute: typeof HarmonizacaoRoute
  KitsRoute: typeof KitsRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  PromocoesRoute: typeof PromocoesRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RecommendationRoute: typeof RecommendationRoute
  RedeemRoute: typeof RedeemRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  SelectorRoute: typeof SelectorRoute
  VantagensRoute: typeof VantagensRoute
  VibeRoute: typeof VibeRoute
  HarmonizacaoResultadoRoute: typeof HarmonizacaoResultadoRoute
  KitIdRoute: typeof KitIdRoute
  ParceiroSlugRoute: typeof ParceiroSlugRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vibe': {
      id: '/vibe'
      path: '/vibe'
      fullPath: '/vibe'
      preLoaderRoute: typeof VibeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vantagens': {
      id: '/vantagens'
      path: '/vantagens'
      fullPath: '/vantagens'
      preLoaderRoute: typeof VantagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selector': {
      id: '/selector'
      path: '/selector'
      fullPath: '/selector'
      preLoaderRoute: typeof SelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation': {
      id: '/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof RecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harmonizacao': {
      id: '/harmonizacao'
      path: '/harmonizacao'
      fullPath: '/harmonizacao'
      preLoaderRoute: typeof HarmonizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube': {
      id: '/clube'
      path: '/clube'
      fullPath: '/clube'
      preLoaderRoute: typeof ClubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiro/$slug': {
      id: '/parceiro/$slug'
      path: '/parceiro/$slug'
      fullPath: '/parceiro/$slug'
      preLoaderRoute: typeof ParceiroSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/$id': {
      id: '/kit/$id'
      path: '/kit/$id'
      fullPath: '/kit/$id'
      preLoaderRoute: typeof KitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harmonizacao_/resultado': {
      id: '/harmonizacao_/resultado'
      path: '/harmonizacao/resultado'
      fullPath: '/harmonizacao/resultado'
      preLoaderRoute: typeof HarmonizacaoResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/$id': {
      id: '/clube/$id'
      path: '/$id'
      fullPath: '/clube/$id'
      preLoaderRoute: typeof ClubeIdRouteImport
      parentRoute: typeof ClubeRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/produtos': {
      id: '/_admin/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminAdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pedidos': {
      id: '/_admin/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminAdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/clientes/': {
      id: '/_admin/admin/clientes/'
      path: '/admin/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminAdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/clientes/$id': {
      id: '/_admin/admin/clientes/$id'
      path: '/admin/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminAdminClientesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminPedidosRoute: typeof AdminAdminPedidosRoute
  AdminAdminProdutosRoute: typeof AdminAdminProdutosRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminClientesIdRoute: typeof AdminAdminClientesIdRoute
  AdminAdminClientesIndexRoute: typeof AdminAdminClientesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminPedidosRoute: AdminAdminPedidosRoute,
  AdminAdminProdutosRoute: AdminAdminProdutosRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminClientesIdRoute: AdminAdminClientesIdRoute,
  AdminAdminClientesIndexRoute: AdminAdminClientesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClubeRouteChildren {
  ClubeIdRoute: typeof ClubeIdRoute
}

const ClubeRouteChildren: ClubeRouteChildren = {
  ClubeIdRoute: ClubeIdRoute,
}

const ClubeRouteWithChildren = ClubeRoute._addFileChildren(ClubeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  ClubeRoute: ClubeRouteWithChildren,
  ConfirmationRoute: ConfirmationRoute,
  ContatoRoute: ContatoRoute,
  HarmonizacaoRoute: HarmonizacaoRoute,
  KitsRoute: KitsRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  PromocoesRoute: PromocoesRoute,
  QuemSomosRoute: QuemSomosRoute,
  RecommendationRoute: RecommendationRoute,
  RedeemRoute: RedeemRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  SelectorRoute: SelectorRoute,
  VantagensRoute: VantagensRoute,
  VibeRoute: VibeRoute,
  HarmonizacaoResultadoRoute: HarmonizacaoResultadoRoute,
  KitIdRoute: KitIdRoute,
  ParceiroSlugRoute: ParceiroSlugRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
